import '../../../core/app_export.dart';
import 'powermetrics_item_model.dart';

/// This class defines the variables used in the [measurement_data_page],
/// and is typically used to hold data that is passed between different parts of the application.
class MeasurementDataModel {
  Rx<List<PowermetricsItemModel>> powermetricsItemList = Rx([
    PowermetricsItemModel(
        activePowerValue: "120,5".obs,
        activePowerUnit: "Kw".obs,
        activePowerLabel: "Active Power".obs,
        apparentPowerValue: "125".obs,
        apparentPowerUnit: "Kw".obs,
        apparentPowerLabel: "Apparent Power".obs,
        dynamicText: "0,78".obs,
        dynamicText1: "Power Quality".obs,
        v1Value: "130,58".obs,
        v1Label: "V1".obs,
        v2Value: "120,78".obs,
        v2Label: "V2".obs,
        v3Value: "126,48".obs,
        v3Label: "V3".obs),
    PowermetricsItemModel(
        activePowerValue: "120,5".obs,
        activePowerUnit: "Kw".obs,
        activePowerLabel: "Active Power".obs,
        apparentPowerValue: "125".obs,
        apparentPowerUnit: "Kw".obs,
        apparentPowerLabel: "Apparent Power".obs,
        dynamicText: "0,78".obs,
        dynamicText1: "Power Quality".obs,
        v1Value: "130,58".obs,
        v1Label: "V1".obs,
        v2Value: "120,78".obs,
        v2Label: "V2".obs,
        v3Value: "126,48".obs,
        v3Label: "V3".obs),
    PowermetricsItemModel(
        activePowerValue: "120,5".obs,
        activePowerUnit: "Kw".obs,
        activePowerLabel: "Active Power".obs,
        apparentPowerValue: "125".obs,
        apparentPowerUnit: "Kw".obs,
        apparentPowerLabel: "Apparent Power".obs,
        dynamicText: "0,78".obs,
        dynamicText1: "Power Quality".obs,
        v1Value: "130,58".obs,
        v1Label: "V1".obs,
        v2Value: "120,78".obs,
        v2Label: "V2".obs,
        v3Value: "126,48".obs,
        v3Label: "V3".obs),
    PowermetricsItemModel(
        activePowerValue: "120,5".obs,
        activePowerUnit: "Kw".obs,
        activePowerLabel: "Active Power".obs,
        apparentPowerValue: "125".obs,
        apparentPowerUnit: "Kw".obs,
        apparentPowerLabel: "Apparent Power".obs,
        dynamicText: "0,78".obs,
        dynamicText1: "Power Quality".obs,
        v1Value: "130,58".obs,
        v1Label: "V1".obs,
        v2Value: "120,78".obs,
        v2Label: "V2".obs,
        v3Value: "126,48".obs,
        v3Label: "V3".obs),
    PowermetricsItemModel(
        activePowerValue: "120,5".obs,
        activePowerUnit: "Kw".obs,
        activePowerLabel: "Active Power".obs,
        apparentPowerValue: "125".obs,
        apparentPowerUnit: "Kw".obs,
        apparentPowerLabel: "Apparent Power".obs,
        dynamicText: "0,78".obs,
        dynamicText1: "Power Quality".obs,
        v1Value: "130,58".obs,
        v1Label: "V1".obs,
        v2Value: "120,78".obs,
        v2Label: "V2".obs,
        v3Value: "126,48".obs,
        v3Label: "V3".obs)
  ]);
}
