import '../../../core/app_export.dart';
import 'viewhierarchy_item_model.dart';
import 'powerusage_item_model.dart';
import 'viewhierarchy1_item_model.dart';
import 'dynamicview_item_model.dart';
import 'viewhierarchy2_item_model.dart';

/// This class defines the variables used in the [measurement_data_two_page],
/// and is typically used to hold data that is passed between different parts of the application.
class MeasurementDataTwoModel {
  Rx<List<ViewhierarchyItemModel>> viewhierarchyItemList = Rx([
    ViewhierarchyItemModel(
        textIN1: "IN1".obs,
        textEightHundredFive: "80,5".obs,
        textKw: "Kw".obs,
        textActivePower: "Active Power".obs,
        textkW: "kW".obs,
        textOneHundred: "100".obs,
        textSeventyFive: "75".obs,
        textFifty: "50".obs,
        textTwentyFive: "25".obs,
        imageVector1064: ImageConstant.imgVector1064.obs,
        textZero: "0".obs,
        textFifteen: "15".obs,
        textThirty: "30".obs,
        textFortyFive: "45".obs,
        textSixty: "60".obs,
        textLast1Hour: "Last 1 hour".obs),
    ViewhierarchyItemModel(
        textIN1: "IN2".obs,
        textEightHundredFive: "65,3".obs,
        textKw: "Kw".obs,
        textActivePower: "Active Power".obs,
        textkW: "kW".obs,
        textOneHundred: "100".obs,
        textSeventyFive: "75".obs,
        textFifty: "50".obs,
        textTwentyFive: "25".obs,
        imageVector1064: ImageConstant.imgVector1064Primary.obs,
        textZero: "0".obs,
        textFifteen: "15".obs,
        textThirty: "30".obs,
        textFortyFive: "45".obs,
        textSixty: "60".obs,
        textLast1Hour: "Last 1 hour".obs),
    ViewhierarchyItemModel(
        textIN1: "IN3".obs,
        textEightHundredFive: "92,1".obs,
        textKw: "Kw".obs,
        textActivePower: "Active Power".obs,
        textkW: "kW".obs,
        textOneHundred: "100".obs,
        textSeventyFive: "75".obs,
        textFifty: "50".obs,
        textTwentyFive: "25".obs,
        imageVector1064: ImageConstant.imgVector1064Primary79x152.obs,
        textZero: "0".obs,
        textFifteen: "15".obs,
        textThirty: "30".obs,
        textFortyFive: "45".obs,
        textSixty: "60".obs,
        textLast1Hour: "Last 1 hour".obs),
    ViewhierarchyItemModel(
        textIN1: "IN4".obs,
        textEightHundredFive: "86,9".obs,
        textKw: "Kw".obs,
        textActivePower: "Active Power".obs,
        textkW: "kW".obs,
        textOneHundred: "100".obs,
        textSeventyFive: "75".obs,
        textFifty: "50".obs,
        textTwentyFive: "25".obs,
        imageVector1064: ImageConstant.imgVector1064Primary47x151.obs,
        textZero: "0".obs,
        textFifteen: "15".obs,
        textThirty: "30".obs,
        textFortyFive: "45".obs,
        textSixty: "60".obs,
        textLast1Hour: "Last 1 hour".obs),
    ViewhierarchyItemModel(
        textIN1: "IN5".obs,
        textEightHundredFive: "54,2".obs,
        textKw: "Kw".obs,
        textActivePower: "Active Power".obs,
        textkW: "kW".obs,
        textOneHundred: "100".obs,
        textSeventyFive: "75".obs,
        textFifty: "50".obs,
        textTwentyFive: "25".obs,
        textZero: "0".obs,
        textFifteen: "15".obs,
        textThirty: "30".obs,
        textFortyFive: "45".obs,
        textSixty: "60".obs,
        textLast1Hour: "Last 1 hour".obs),
    ViewhierarchyItemModel(
        textIN1: "IN6".obs,
        textEightHundredFive: "71,2".obs,
        textKw: "Kw".obs,
        textActivePower: "Active Power".obs,
        textkW: "kW".obs,
        textOneHundred: "100".obs,
        textSeventyFive: "75".obs,
        textFifty: "50".obs,
        textTwentyFive: "25".obs,
        textZero: "0".obs,
        textFifteen: "15".obs,
        textThirty: "30".obs,
        textFortyFive: "45".obs,
        textSixty: "60".obs,
        textLast1Hour: "Last 1 hour".obs)
  ]);

  Rx<List<PowerusageItemModel>> powerusageItemList = Rx([
    PowerusageItemModel(
        title: "IN1".obs,
        value1: "56,5".obs,
        unit1: "Kw".obs,
        title2: "Apparent Power".obs,
        unit2: "kW".obs,
        value2: "100".obs,
        value3: "75".obs,
        value4: "50".obs,
        value5: "25".obs,
        image2: ImageConstant.imgVector1064.obs,
        value6: "0".obs,
        value7: "15".obs,
        value8: "30".obs,
        value9: "45".obs,
        value10: "60".obs,
        title3: "Last 1 hour".obs),
    PowerusageItemModel(
        title: "IN2".obs,
        value1: "51,2".obs,
        unit1: "Kw".obs,
        title2: "Apparent Power".obs,
        unit2: "kW".obs,
        value2: "100".obs,
        value3: "75".obs,
        value4: "50".obs,
        value5: "25".obs,
        image2: ImageConstant.imgVector1064.obs,
        value6: "0".obs,
        value7: "15".obs,
        value8: "30".obs,
        value9: "45".obs,
        value10: "60".obs,
        title3: "Last 1 hour".obs),
    PowerusageItemModel(
        title: "IN3".obs,
        value1: "68,8".obs,
        unit1: "Kw".obs,
        title2: "Apparent Power".obs,
        unit2: "kW".obs,
        value2: "100".obs,
        value3: "75".obs,
        value4: "50".obs,
        value5: "25".obs,
        image2: ImageConstant.imgVector1064Primary43x152.obs,
        value6: "0".obs,
        value7: "15".obs,
        value8: "30".obs,
        value9: "45".obs,
        value10: "60".obs,
        title3: "Last 1 hour".obs),
    PowerusageItemModel(
        title: "IN4".obs,
        value1: "61,4".obs,
        unit1: "Kw".obs,
        title2: "Apparent Power".obs,
        unit2: "kW".obs,
        value2: "100".obs,
        value3: "75".obs,
        value4: "50".obs,
        value5: "25".obs,
        value6: "0".obs,
        value7: "15".obs,
        value8: "30".obs,
        value9: "45".obs,
        value10: "60".obs,
        title3: "Last 1 hour".obs),
    PowerusageItemModel(
        title: "IN5".obs,
        value1: "32,9".obs,
        unit1: "Kw".obs,
        title2: "Apparent Power".obs,
        unit2: "kW".obs,
        value2: "100".obs,
        value3: "75".obs,
        value4: "50".obs,
        value5: "25".obs,
        value6: "0".obs,
        value7: "15".obs,
        value8: "30".obs,
        value9: "45".obs,
        value10: "60".obs,
        title3: "Last 1 hour".obs),
    PowerusageItemModel(
        title: "IN6".obs,
        value1: "71,0".obs,
        unit1: "Kw".obs,
        title2: "Apparent Power".obs,
        unit2: "kW".obs,
        value2: "100".obs,
        value3: "75".obs,
        value4: "50".obs,
        value5: "25".obs,
        image2: ImageConstant.imgVector1064Primary47x152.obs,
        value6: "0".obs,
        value7: "15".obs,
        value8: "30".obs,
        value9: "45".obs,
        value10: "60".obs,
        title3: "Last 1 hour".obs)
  ]);

  Rx<List<Viewhierarchy1ItemModel>> viewhierarchy1ItemList = Rx([
    Viewhierarchy1ItemModel(
        textIN1: "IN1".obs,
        textEightyEight: "0,88".obs,
        textCos: "Cos ϕ".obs,
        textCosPhi: "Cos Phi".obs,
        textCos1: "Cos ϕ".obs,
        textOne: "1".obs,
        textSeventyFive: "0,75".obs,
        textFifty: "0,50".obs,
        textTwentyFive: "0,25".obs,
        imageVector1064: ImageConstant.imgVector1064Primary36x152.obs,
        textZero: "0".obs,
        textFifteen: "15".obs,
        textThirty: "30".obs,
        textFortyFive: "45".obs,
        textSixty: "60".obs,
        textLast1Hour: "Last 1 hour".obs),
    Viewhierarchy1ItemModel(
        textIN1: "IN2".obs,
        textEightyEight: "0,92".obs,
        textCos: "Cos ϕ".obs,
        textCosPhi: "Cos Phi".obs,
        textCos1: "Cos ϕ".obs,
        textOne: "1".obs,
        textSeventyFive: "0,75".obs,
        textFifty: "0,50".obs,
        textTwentyFive: "0,25".obs,
        imageVector1064: ImageConstant.imgVector1064Primary36x152.obs,
        textZero: "0".obs,
        textFifteen: "15".obs,
        textThirty: "30".obs,
        textFortyFive: "45".obs,
        textSixty: "60".obs,
        textLast1Hour: "Last 1 hour".obs),
    Viewhierarchy1ItemModel(
        textIN1: "IN3".obs,
        textEightyEight: "0,95".obs,
        textCos: "Cos ϕ".obs,
        textCosPhi: "Cos Phi".obs,
        textCos1: "Cos ϕ".obs,
        textOne: "1".obs,
        textSeventyFive: "0,75".obs,
        textFifty: "0,50".obs,
        textTwentyFive: "0,25".obs,
        imageVector1064: ImageConstant.imgVector1064Primary32x152.obs,
        textZero: "0".obs,
        textFifteen: "15".obs,
        textThirty: "30".obs,
        textFortyFive: "45".obs,
        textSixty: "60".obs,
        textLast1Hour: "Last 1 hour".obs),
    Viewhierarchy1ItemModel(
        textIN1: "IN4".obs,
        textEightyEight: "0,78".obs,
        textCos: "Cos ϕ".obs,
        textCosPhi: "Cos Phi".obs,
        textCos1: "Cos ϕ".obs,
        textOne: "1".obs,
        textSeventyFive: "0,75".obs,
        textFifty: "0,50".obs,
        textTwentyFive: "0,25".obs,
        imageVector1064: ImageConstant.imgVector1064Primary23x152.obs,
        textZero: "0".obs,
        textFifteen: "15".obs,
        textThirty: "30".obs,
        textFortyFive: "45".obs,
        textSixty: "60".obs,
        textLast1Hour: "Last 1 hour".obs),
    Viewhierarchy1ItemModel(
        textIN1: "IN5".obs,
        textEightyEight: "0,84".obs,
        textCos: "Cos ϕ".obs,
        textCosPhi: "Cos Phi".obs,
        textCos1: "Cos ϕ".obs,
        textOne: "1".obs,
        textSeventyFive: "0,75".obs,
        textFifty: "0,50".obs,
        textTwentyFive: "0,25".obs,
        imageVector1064: ImageConstant.imgVector1064Primary24x152.obs,
        textZero: "0".obs,
        textFifteen: "15".obs,
        textThirty: "30".obs,
        textFortyFive: "45".obs,
        textSixty: "60".obs,
        textLast1Hour: "Last 1 hour".obs),
    Viewhierarchy1ItemModel(
        textIN1: "IN6".obs,
        textEightyEight: "0,98".obs,
        textCos: "Cos ϕ".obs,
        textCosPhi: "Cos Phi".obs,
        textCos1: "Cos ϕ".obs,
        textOne: "1".obs,
        textSeventyFive: "0,75".obs,
        textFifty: "0,50".obs,
        textTwentyFive: "0,25".obs,
        textZero: "0".obs,
        textFifteen: "15".obs,
        textThirty: "30".obs,
        textFortyFive: "45".obs,
        textSixty: "60".obs,
        textLast1Hour: "Last 1 hour".obs)
  ]);

  Rx<List<DynamicviewItemModel>> dynamicviewItemList = Rx([
    DynamicviewItemModel(
        text1: "IN1".obs,
        text2: "223".obs,
        text3: "V".obs,
        text4: "Voltage".obs,
        text5: "V".obs,
        text6: "400".obs,
        text7: "300".obs,
        text8: "200".obs,
        text9: "100".obs,
        image2: ImageConstant.imgVector1064Primary36x152.obs,
        text10: "0".obs,
        text11: "15".obs,
        text12: "30".obs,
        text13: "45".obs,
        text14: "60".obs,
        text15: "Last 1 hour".obs),
    DynamicviewItemModel(
        text1: "IN2".obs,
        text2: "232".obs,
        text3: "V".obs,
        text4: "Voltage".obs,
        text5: "V".obs,
        text6: "400".obs,
        text7: "300".obs,
        text8: "200".obs,
        text9: "100".obs,
        text10: "0".obs,
        text11: "15".obs,
        text12: "30".obs,
        text13: "45".obs,
        text14: "60".obs,
        text15: "Last 1 hour".obs),
    DynamicviewItemModel(
        text1: "IN3".obs,
        text2: "385".obs,
        text3: "V".obs,
        text4: "Voltage".obs,
        text5: "V".obs,
        text6: "400".obs,
        text7: "300".obs,
        text8: "200".obs,
        text9: "100".obs,
        text10: "0".obs,
        text11: "15".obs,
        text12: "30".obs,
        text13: "45".obs,
        text14: "60".obs,
        text15: "Last 1 hour".obs),
    DynamicviewItemModel(
        text1: "IN4".obs,
        text2: "230".obs,
        text3: "V".obs,
        text4: "Voltage".obs,
        text5: "V".obs,
        text6: "400".obs,
        text7: "300".obs,
        text8: "200".obs,
        text9: "100".obs,
        text10: "0".obs,
        text11: "15".obs,
        text12: "30".obs,
        text13: "45".obs,
        text14: "60".obs,
        text15: "Last 1 hour".obs),
    DynamicviewItemModel(
        text1: "IN5".obs,
        text2: "391".obs,
        text3: "V".obs,
        text4: "Voltage".obs,
        text5: "V".obs,
        text6: "400".obs,
        text7: "300".obs,
        text8: "200".obs,
        text9: "100".obs,
        text10: "0".obs,
        text11: "15".obs,
        text12: "30".obs,
        text13: "45".obs,
        text14: "60".obs,
        text15: "Last 1 hour".obs),
    DynamicviewItemModel(
        text1: "IN6".obs,
        text2: "228".obs,
        text3: "V".obs,
        text4: "Voltage".obs,
        text5: "V".obs,
        text6: "400".obs,
        text7: "300".obs,
        text8: "200".obs,
        text9: "100".obs,
        image2: ImageConstant.imgVector1064Primary31x152.obs,
        text10: "0".obs,
        text11: "15".obs,
        text12: "30".obs,
        text13: "45".obs,
        text14: "60".obs,
        text15: "Last 1 hour".obs)
  ]);

  Rx<List<Viewhierarchy2ItemModel>> viewhierarchy2ItemList = Rx([
    Viewhierarchy2ItemModel(
        textIN1: "IN1".obs,
        textFortyEight: "48".obs,
        textH: "H".obs,
        textFrequency: "Frequency".obs,
        textH1: "H".obs,
        textEighty: "80".obs,
        textSixty: "60".obs,
        textForty: "40".obs,
        textTwenty: "20".obs,
        imageVector1064: ImageConstant.imgVector1064Primary36x152.obs,
        textZero: "0".obs,
        textFifteen: "15".obs,
        textThirty: "30".obs,
        textFortyFive: "45".obs,
        textSixty1: "60".obs,
        textLast1Hour: "Last 1 hour".obs),
    Viewhierarchy2ItemModel(
        textIN1: "IN2".obs,
        textFortyEight: "47".obs,
        textH: "H".obs,
        textFrequency: "Frequency".obs,
        textH1: "H".obs,
        textEighty: "80".obs,
        textSixty: "60".obs,
        textForty: "40".obs,
        textTwenty: "20".obs,
        textZero: "0".obs,
        textFifteen: "15".obs,
        textThirty: "30".obs,
        textFortyFive: "45".obs,
        textSixty1: "60".obs,
        textLast1Hour: "Last 1 hour".obs),
    Viewhierarchy2ItemModel(
        textIN1: "IN3".obs,
        textFortyEight: "50,1".obs,
        textH: "H".obs,
        textFrequency: "Frequency".obs,
        textH1: "H".obs,
        textEighty: "80".obs,
        textSixty: "60".obs,
        textForty: "40".obs,
        textTwenty: "20".obs,
        textZero: "0".obs,
        textFifteen: "15".obs,
        textThirty: "30".obs,
        textFortyFive: "45".obs,
        textSixty1: "60".obs,
        textLast1Hour: "Last 1 hour".obs),
    Viewhierarchy2ItemModel(
        textIN1: "IN4".obs,
        textFortyEight: "53,2".obs,
        textH: "H".obs,
        textFrequency: "Frequency".obs,
        textH1: "H".obs,
        textEighty: "80".obs,
        textSixty: "60".obs,
        textForty: "40".obs,
        textTwenty: "20".obs,
        imageVector1064: ImageConstant.imgVector106427x152.obs,
        textZero: "0".obs,
        textFifteen: "15".obs,
        textThirty: "30".obs,
        textFortyFive: "45".obs,
        textSixty1: "60".obs,
        textLast1Hour: "Last 1 hour".obs),
    Viewhierarchy2ItemModel(
        textIN1: "IN5".obs,
        textFortyEight: "48,6".obs,
        textH: "H".obs,
        textFrequency: "Frequency".obs,
        textH1: "H".obs,
        textEighty: "80".obs,
        textSixty: "60".obs,
        textForty: "40".obs,
        textTwenty: "20".obs,
        textZero: "0".obs,
        textFifteen: "15".obs,
        textThirty: "30".obs,
        textFortyFive: "45".obs,
        textSixty1: "60".obs,
        textLast1Hour: "Last 1 hour".obs),
    Viewhierarchy2ItemModel(
        textIN1: "IN6".obs,
        textFortyEight: "50".obs,
        textH: "H".obs,
        textFrequency: "Frequency".obs,
        textH1: "H".obs,
        textEighty: "80".obs,
        textSixty: "60".obs,
        textForty: "40".obs,
        textTwenty: "20".obs,
        textZero: "0".obs,
        textFifteen: "15".obs,
        textThirty: "30".obs,
        textFortyFive: "45".obs,
        textSixty1: "60".obs,
        textLast1Hour: "Last 1 hour".obs)
  ]);
}
